#!/bin/bash

###########
# usage: ./makebox <case>
#
# script pased on by Pablo Brubeck
###########

case=$1

core=$HOME"/Nek5000/bin/"
sfx='box'
box=$case'.'$sfx

## modify box
#sed -i "/nelx,nely,nelz for Box/c\-"$2" -"$3" -"$4"   nelx,nely,nelz for Box" $case".box"

$core'genbox' << DOF
$box
DOF

$core'reatore2' << DOF
$sfx
$case
DOF

rm box.rea box.re2

$core'genmap' << DOF
$case
0.1
DOF
