#!/bin/bash

#
# usage: $ ./makebox <case>
#

case=$1

core=$HOME"/Nek5000/bin/"
sfx='box'
boxfile=$case'.'$sfx

## modify box
#sed -i "/nelx,nely,nelz for Box/c\-"$2" -"$3" -"$4"   nelx,nely,nelz for Box" $case".box"

$core'genbox' << DOF
$boxfile
DOF

$core'reatore2' << DOF
$sfx
$case
DOF

$core'genmap' << DOF
$case
0.1
DOF

rm -f box.rea box.re2
